version: 2
jobs:
  build:
    docker:
      - image: golang
    working_directory: /go/src/github.com/raviqqe/parcom
    steps:
      - checkout
      - run: go get -d -t ./...
      - run: go get -u github.com/alecthomas/gometalinter
      - run: $GOPATH/bin/gometalinter --install
      - run: $GOPATH/bin/gometalinter ./...
      - run: go build ./...
      - run: go test -covermode atomic -coverprofile coverage.txt -race ./...
      - run: curl -s https://codecov.io/bash | bash
